stages:
  - deploy

deploy_to_railway:
  stage: deploy
  image: python:3.12
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install railway
    - railway login --api-token $RAILWAY_API_TOKEN
  script:
    - railway up --service file-extractor 
  only:
    - main