stages:
  - deploy

deploy_to_railway:
  stage: deploy
  image: python:3.12
  variables:
    RAILWAY_TOKEN: $RAILWAY_API_TOKEN
  before_script:
    - pip install --break-system-packages railway
  script:
    - echo "Railway Token: ${RAILWAY_TOKEN:0:5}****"
    - which railway
    - RAILWAY_DEBUG=1 railway up --service file-extractor
  only:
    - main