stages:
  - deploy

deploy_to_railway:
  stage: deploy
  image: python:3.12
  before_script:
    - pip install --upgrade pip
    - pip install railway --break-system-packages  # Installiere Railway CLI
    - pip install railway --break-system-packages
    - python -m railway login --api-token $RAILWAY_API_TOKEN
  script:
    - python -m railway up --service file-extractor
  only:
    - main