stages:
  - deploy

deploy_to_railway:
  stage: deploy
  image: python:3.12
  variables:
    RAILWAY_TOKEN: $RAILWAY_API_TOKEN  # Sicherstellen, dass das Token gesetzt ist
  before_script:
    - pip install --break-system-packages railway  # Globale Installation
  script:
    - echo "Railway Token: ${RAILWAY_TOKEN:0:5}****"  # Debugging
    - which railway  # Prüfen, wo railway installiert ist
    - RAILWAY_DEBUG=1 railway up --service file-extractor  # Debug-Modus für bessere Logs
  only:
    - main