stages:
  - deploy

deploy_to_railway:
  stage: deploy
  image: python:3.12
  before_script:
    - pip install --upgrade pip
    - pip install railway --break-system-packages
    - find / -name "railway" 2>/dev/null
  script:
    - python -m railway up --service file-extractor
  only:
    - main