stages:
  - deploy

deploy_to_railway:
  stage: deploy
  image: python:3.12  # Verwende eine passende Python-Version
  before_script:
    - pip install railway  # Railway CLI installieren
    - railway login --api-token $RAILWAY_API_TOKEN  # Sicheres Login mit Token
  script:
    - railway up --service file-extractor  # Service deployen
  only:
    - main  # Nur auf dem main-Branch ausführen